### ISSUE TITLE
lineageos 18.1 not booting

### ISSUE THREAD

**Issue by rik0612c** [ivanmeler/android_device_samsung_heroqlte#1]
successfully built lineage os 18.1 for heroqlte using the repos from Local manifest, but the device stucks on splash screen.

my device is a SM-G9300 (China Variant)

**Comment by ivanmeler** [comment]
Oh hey this is still work in progress as im waiting for device to arrive so i can properly finish bring up of source.
You will notice more activity on repos once device arrives to me

**Comment by rik0612c** [comment]
Ok i see, would like to wait until it finishes. Thanks for the reply.

**Comment by ivanmeler** [comment]
@rik0612c it boots now, there are still quite a bit of things to fix but ill do that in coming days, and then update it to 19.1 and 20.0

**Comment by rik0612c** [comment]
> @rik0612c it boots now, there are still quite a bit of things to fix but ill do that in coming days, and then update it to 19.1 and 20.0

oh it sounds great. Big thanks for your work. i will give it a try.
