### ISSUE TITLE
lineage-19.1 bootloop problem

### ISSUE THREAD

**Issue by CharmingMeteorite** [ivanmeler/android_device_samsung_heroqlte#2]
After successfully building lineageos18.1 and starting successfully in heroqltechn, I tried to build lineage19.1 branch, but after the build was successful, I flashed it to heroqltechn, it got stuck in bootloop and I could only see the Samsung logo, It will automatically restart to the Samsung logo after a while,cannot boot to os. I tried flashing the recovery.img in the zip and after the Samsung logo went off, the screen went dark and no response. I tried rebuilding but to no avail, what's wrong?

**Comment by ivanmeler** [comment]
i didnt compile 19.1 in 2 months, last time i did it worked however. Have you applied patches from github.com/8890q/patches ? they are needed. there is specific qcom apply script you can use

**Comment by CharmingMeteorite** [comment]
> i didnt compile 19.1 in 2 months, last time i did it worked however. Have you applied patches from github.com/8890q/patches ? they are needed. there is specific qcom apply script you can use

Ok, I didn't know the patches, I will continue to try it later, thanks for your reply

**Comment by ivanmeler** [comment]
with patches apply it will work, this is required due to lack of bpf in 3.18 kernel

**Comment by CharmingMeteorite** [comment]
> with patches apply it will work, this is required due to lack of bpf in 3.18 kernel

Okay, it's working now，thanks for your help，At the same time, I noticed that when I entered recovery mode, I cannt exit, force restart will start to the recovery mode by default.In recovery mode I can only see a twrp logo without any button,I use latest twrp offical build, is there any way to solve this problem?

**Comment by ivanmeler** [comment]
yes official twrp is missing this commit https://github.com/TeamWin/android_device_oneplus_oneplus3t/commit/15e58298f87c5b653d31bf609e853a0f6f7f091e

you can manually empty it with 

dd if=/dev/zero of=/dev/block/bootdevice/by-name/misc or add that commit in twrp, i was sort of too lazy to send pull request for official twrp

**Comment by CharmingMeteorite** [comment]
> yes official twrp is missing this commit [TeamWin/android_device_oneplus_oneplus3t@15e5829](https://githubfast.com/TeamWin/android_device_oneplus_oneplus3t/commit/15e58298f87c5b653d31bf609e853a0f6f7f091e)
> 
> you can manually empty it with
> 
> dd if=/dev/zero of=/dev/block/bootdevice/by-name/misc or add that commit in twrp, i was sort of too lazy to send pull request for official twrp

OK I got it, thanks for your reply.Also, appreciate your contribution to Qcom S7
